# Generated by Django 5.2.12 on 2026-03-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_product_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sale',
        ),
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Стоимость'),
        ),
    ]
