# Generated by Django 5.2.12 on 2026-04-01 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_order_address_alter_order_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='rejection_reason',
            new_name='reject_reason',
        ),
    ]
