# Generated by Django 5.2.12 on 2026-05-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_rejection_reason_order_reject_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='username', max_length=120, verbose_name='Логин'),
        ),
    ]
